### PR TITLE
Run README.md through prettier and fix some typos

### PR DESCRIPTION
**Pull request by triallax**
Please merge #7 and #5 before this so that I can re-run Prettier on `README.md`.

### CODE REVIEW

**Comment by milesfrain** [comment]
Looks like we're missing some stuff from #7 and #5. Ping me when it's ready to merge.

**Comment by triallax** [comment]
Yup, I made a mistake in my merging. Will fix it right away.

**Comment by triallax** [comment]
I think I've made too many commits. Should I squash them?

**Comment by milesfrain** [comment]
Github's "squash and merge" button will do this automatically.

**Pull request merged**
